In [1]:
import torch

In [30]:
x=torch.tensor([5,3])

In [31]:
y=x.new_ones(5, 3, dtype=torch.double)

In [43]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [47]:
y

tensor([ 0.1456,  0.1952, -1.7302, -1.0314, -0.0547, -0.5385, -0.0485, -0.5028,
        -0.7645, -0.5979, -1.1349, -0.3781, -1.1631, -1.0216, -0.6056,  0.6287])

In [51]:
torch.cuda.is_available()

True

In [52]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

tensor([[ 2.0000,  1.1952, -0.7302, -0.0314],
        [ 0.9453,  0.4615,  0.9515,  0.4972],
        [ 0.2355,  0.4021, -0.1349,  0.6219],
        [-0.1631, -0.0216,  0.3944,  1.6287]], device='cuda:0')
tensor([[ 2.0000,  1.1952, -0.7302, -0.0314],
        [ 0.9453,  0.4615,  0.9515,  0.4972],
        [ 0.2355,  0.4021, -0.1349,  0.6219],
        [-0.1631, -0.0216,  0.3944,  1.6287]], dtype=torch.float64)
