In [1]:
import math
import os
import random
import sys
from collections import Counter

import jieba
import nltk
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [61]:
ax=[[5]*random.randint(1,5) for _ in range(10)]

In [17]:
a=[   2,    8.242,   22,  311, 1511,    4,    3]

In [9]:
torch.tensor(len(a)).unsqueeze(0)

tensor([7])

In [15]:
torch.Tensor([[1.2323242]]).long()

tensor([[1]])

In [21]:
torch.tensor(a).long()

tensor([   2,    8,   22,  311, 1511,    4,    3])

In [23]:
kk=torch.tensor([[ 3866,  2259,   835,   167,   167, 11149,  5841,  9945,  4254,   166]])

In [24]:
kk

tensor([[ 3866,  2259,   835,   167,   167, 11149,  5841,  9945,  4254,   166]])

In [26]:
kk.numpy()

array([[ 3866,  2259,   835,   167,   167, 11149,  5841,  9945,  4254,
          166]], dtype=int64)

In [ ]:
tensor([[[-1.0000, -0.9288,  0.9860,  0.9857, -0.9990, -0.9995,  0.9949,
          -0.9910,  0.9881, -0.9482, -0.9890, -0.1382, -0.8301,  0.9970,
           0.9114, -0.8964, -0.9575,  0.9354,  0.9043, -0.9950, -0.9123,
           0.9979, -0.9829,  0.8384, -0.9982, -0.9997,  0.9941, -0.9314,
           0.9990, -0.9996,  0.9975, -0.7433, -0.9127,  0.9952, -0.6198,
          -0.9998, -0.9960,  0.9043,  0.9996, -0.9631,  0.9978, -0.8762,
           0.9959,  0.9935, -0.9991, -0.8219,  0.9982, -0.9728, -0.9884,
           1.0000, -0.9332,  0.9980,  0.9336, -0.2239, -0.9996,  1.0000,
           1.0000,  0.7955,  0.8613, -0.7487,  0.9965,  0.9972,  0.8966,
           0.9628, -0.7322,  0.9948, -0.8320,  0.9917,  0.9996, -0.9996,
          -0.9708,  0.2274, -0.9999,  0.6706, -0.3952, -0.9709, -0.9993,
           0.9969, -0.9446,  1.0000, -0.1499, -0.9926, -0.1259, -0.9960,
           0.9740,  0.9993,  0.9656, -0.9712, -0.9961,  0.9867,  0.9849,
           0.9265,  0.9915,  0.9974, -0.9979, -0.7751,  0.4445, -1.0000,
           0.4417, -0.9927]]])